title: Bogdan Guranda
description: Personal website
baseurl: ""
url: "https://bogdanguranda.github.io"
permalink: pretty

author:
  name: Bogdan Guranda
  github: bogdanguranda
  linkedin: bogdan-guranda

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: category
  - scope:
      path: ""
    values:
      layout: category

# ─── Navigation ───
nav:
  - title: Contact
    url: /
  - title: Games
    url: /games/
    subnav:
      - title: Logikids (Bacherlor's Thesis)
        url: /games/logikids/
  - title: Trading
    url: /trading/
    subnav:
      - title: Trading Algo
        url: /trading/trading-algo/
      - title: Trading Assistant
        url: /trading/trading-assistant/
      - title: Trading Assistant Discord Bot
        url: /trading/trading-assistant-discord-bot/
      - title: Trading Risk Manager
        url: /trading/trading-risk-manager/
      - title: Trading Quotes X
        url: /trading/trading-quotes-x/
  - title: Blog
    url: /blog/
    subnav:
      - title: Trading
        url: /blog/trading/
      - title: Coding
        url: /blog/coding/
      - title: History
        url: /blog/history/
      - title: Books
        url: /blog/books/
      - title: Travels
        url: /blog/travels/
