title: Bogdan Guranda
description: Personal website
baseurl: ""
url: "https://bogdanguranda.github.io"
permalink: pretty

author:
  name: Bogdan Guranda
  github: bogdanguranda
  linkedin: bogdan-guranda

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: category
  - scope:
      path: ""
    values:
      layout: category

# ─── Navigation ───
nav:
  - title: Contact
    url: /
  - title: Apps
    url: /apps/
    subnav:
      - title: Games
        url: /apps/games/
        subnav:
          - title: Logikids (Bachelor's Thesis)
            url: /apps/games/logikids/
      - title: Trading
        url: /apps/trading/
        subnav:
          - title: Trading Algo
            url: /apps/trading/trading-algo/
          - title: Trading Assistant
            url: /apps/trading/trading-assistant/
          - title: Trading Assistant Discord Bot
            url: /apps/trading/trading-assistant-discord-bot/
          - title: Trading Risk Manager
            url: /apps/trading/trading-risk-manager/
          - title: Trading Quotes X
            url: /apps/trading/trading-quotes-x/
  - title: Blog
    url: /blog/
    subnav:
      - title: Trading
        url: /blog/trading/
      - title: Coding
        url: /blog/coding/
      - title: History
        url: /blog/history/
      - title: Books
        url: /blog/books/
      - title: Travels
        url: /blog/travels/
